- name: Copy SpamAssasin Rules 
  become: yes 
  hosts: mail 
  tasks: 
   - name: 'Copy 99_wentor.cf to zimbra mail' 
     ansible.builtin.copy: 
       src: files/99_wentor.cf 
       dest: /opt/zimbra/data/spamassassin/rules/99_rules.cf 
       owner: root 
       group: root 
       mode: '0644' 
   - name: Restart Zimbra 
     ansible.builtin.command: zmcontrol restart 
     become: yes 
     become_user: zimbra
   - name: "Build hosts file"
     lineinfile: dest=/etc/hosts line="{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" state=present
     with_items: {{groups['ch']}}